export default [
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/blackpearl.jpg",
    "gameTypes": "SWF",
    "gameId": 2757,
    "tag": "CGModule,Slots,Egaming,Promo",
    "label": "Black Pearl",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2757\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/fruitjack.jpg",
    "gameTypes": "SWF",
    "gameId": 2758,
    "tag": "CGModule,Slots,Egaming,Promo",
    "label": "FruitJack",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2758\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/huntersdream2.jpg",
    "gameTypes": "SWF",
    "gameId": 2759,
    "tag": "CGModule,Slots,Egaming,Promo",
    "label": "Hunter's Dream 2",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2759\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/multiplay81.jpg",
    "gameTypes": "SWF",
    "gameId": 2760,
    "tag": "CGModule,Slots,Egaming,Promo",
    "label": "Multiplay 81",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2760\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/superstar27.jpg",
    "gameTypes": "SWF",
    "gameId": 2761,
    "tag": "CGModule,Slots,Egaming,Promo",
    "label": "Super Star 27",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2761\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/triplewildseven.jpg",
    "gameTypes": "SWF",
    "gameId": 2762,
    "tag": "CGModule,Slots,Egaming,Promo",
    "label": "Triple Wild Seven",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2762\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/amazonsbattle.jpg",
    "gameTypes": "SWF",
    "gameId": 2741,
    "tag": "CGModule,Slots,EGT,Promo",
    "label": "Amazons' Battle",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2741\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/caramelhot.jpg",
    "gameTypes": "SWF",
    "gameId": 2742,
    "tag": "CGModule,Slots,EGT,Promo",
    "label": "Caramel Hot",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2742\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/circusbrilliant.jpg",
    "gameTypes": "SWF",
    "gameId": 2743,
    "tag": "CGModule,Slots,EGT,Promo",
    "label": "Circus Brilliant",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2743\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/extremelyhot.jpg",
    "gameTypes": "SWF",
    "gameId": 2744,
    "tag": "CGModule,Slots,EGT,Promo",
    "label": "Extremely Hot",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2744\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/versaillesgold.jpg",
    "gameTypes": "SWF",
    "gameId": 2745,
    "tag": "CGModule,Slots,EGT,Promo",
    "label": "Versailles Gold",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2745\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/arisingphoenix.jpg",
    "gameTypes": "HTML5_PC_COMPATIBLE",
    "gameId": 3312,
    "tag": "CGModule,Slots,Amatic,Promo",
    "label": "Arising Phoenix",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/3312\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/book-of-fortune.jpg",
    "gameTypes": "HTML5_PC_COMPATIBLE",
    "gameId": 3306,
    "tag": "CGModule,Slots,Amatic,Promo",
    "label": "Book of Fortune",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/3306\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/wildstars.jpg",
    "gameTypes": "HTML5_PC_COMPATIBLE",
    "gameId": 3314,
    "tag": "CGModule,Slots,Amatic,Promo",
    "label": "Wild Stars",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/3314\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/admiralnelson.jpg",
    "gameTypes": "HTML5_PC_COMPATIBLE",
    "gameId": 3259,
    "tag": "CGModule,Slots,Amatic,Promo",
    "label": "Admiral Nelson",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/3259\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/africanriches.jpg",
    "gameTypes": "SWF",
    "gameId": 1378,
    "tag": "CGModule,Slots,GTECH,Promo",
    "label": "African Riches",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/1378\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/amazons.jpg",
    "gameTypes": "SWF",
    "gameId": 749,
    "tag": "CGModule,Slots,QBR,Promo",
    "label": "Amazons",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/749\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/americanroulette-ne.jpg",
    "gameTypes": "SWF",
    "gameId": 2202,
    "tag": "CGModule,Roulette,Netent,Promo",
    "label": "American Roulette",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/2202\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/avalon.jpg",
    "gameTypes": "SWF",
    "gameId": 751,
    "tag": "CGModule,Slots,Micro,Promo",
    "label": "Avalon",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/751\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/aztec.jpg",
    "gameTypes": "SWF",
    "gameId": 1569,
    "tag": "CGModule,Slots,RTG,Promo",
    "label": "Aztec's Treasure",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/1569\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/beetlemania.jpg",
    "gameTypes": "SWF",
    "gameId": 736,
    "tag": "CGModule,Slots,Novo,Promo",
    "label": "Beetle Mania",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/736\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/bells-on-fire.jpg",
    "gameTypes": "HTML5_PC_COMPATIBLE",
    "gameId": 3298,
    "tag": "CGModule,Slots,Amatic,Promo",
    "label": "Bells On Fire",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/3298\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/bestofbook.jpg",
    "gameTypes": "SWF",
    "gameId": 950,
    "tag": "CGModule,Slots,Mcreel,Promo",
    "label": "Best Of Book",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/950\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/bigeasy.jpg",
    "gameTypes": "SWF",
    "gameId": 1379,
    "tag": "CGModule,Slots,GTECH,Promo",
    "label": "The Big Easy",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/1379\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/blackpearl.jpg",
    "gameTypes": "SWF",
    "gameId": 754,
    "tag": "CGModule,Slots,QBR,Promo",
    "label": "BlackPearl",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/754\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/bloodsuckers.jpg",
    "gameTypes": "SWF",
    "gameId": 735,
    "tag": "CGModule,Slots,Netent,Promo",
    "label": "Blood Suckers",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/735\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/book-of-aztec.jpg",
    "gameTypes": "HTML5_PC_COMPATIBLE",
    "gameId": 3305,
    "tag": "CGModule,Slots,Amatic,Promo",
    "label": "Book of Aztec",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/3305\/fullscreen\/",
    "promolink": false
  },
  {
    "logoUrl": "http:\/\/yuli-belitskaya.com\/img-react\/bookofra.jpg",
    "gameTypes": "SWF",
    "gameId": 760,
    "tag": "CGModule,Slots,Novo,Promo",
    "label": "Book Of Ra",
    "view": "game",
    "supportDemo": true,
    "url": "\/it\/zipbuy\/games\/game\/760\/fullscreen\/",
    "promolink": false
  }
]
